services:
  database:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=bigmakk'
      - 'POSTGRES_DB=easier'
      - 'POSTGRES_PASSWORD=@26October'
    volumes:
      - './volumes/bigmakk/postgres:/var/lib/postgres/data'
